version: '3.8'
services:
  drupal:
    image: drupal:latest
    ports:
      - "8080:8080"
    volumes:
      - drupal_data:/var/www/html
    restart: always
    environment:
      - DRUPAL_DB_HOST=db
      - DRUPAL_DB_USER=root
      - DRUPAL_DB_PASSWORD=root
      - DRUPAL_DB_NAME=drupal
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql
volumes:
  drupal_data:
  db_data: